# Generated by Django 5.1 on 2024-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_raise_request_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_tr_nd_histry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('main_tr_slno', models.IntegerField(blank=True, null=True)),
                ('resp', models.IntegerField(default=0)),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(default='Created', max_length=500)),
                ('createdby', models.CharField(blank=True, max_length=500, null=True)),
                ('delete1', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='attach_file_original',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='attach_file_rename',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='rqstnr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
