# Generated by Django 5.1 on 2024-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_main_tr_nd_histry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_tr_nd_histry',
            name='id',
        ),
        migrations.AlterField(
            model_name='main_tr_nd_histry',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
