# Generated by Django 5.1 on 2024-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_main_tr_nd_histry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='approve_sts',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='delete1',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='tag_confirm_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Approved'), (2, 'Clarification needed'), (3, 'Skipped'), (4, 'Tag assigned for developer for future work')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='usr_sts',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
