# Generated by Django 5.1 on 2024-09-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_raise_request_documentation_approve_sts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='approve_type',
            field=models.CharField(blank=True, default='Y', max_length=10, null=True),
        ),
    ]
