# Generated by Django 5.1 on 2024-09-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_raise_request_documentation_approve_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='tag_confirm_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Approved'), (2, 'Clarification needed'), (3, 'Skipped'), (4, 'Tag assigned for developer for future work')], null=True),
        ),
    ]
