# Generated by Django 5.1 on 2024-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_raise_request_documentation_tag_confirm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
