# Generated by Django 5.1 on 2024-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_raise_request_documentation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='approve_type',
            field=models.IntegerField(choices=[(1, 'Waiting for approval'), (2, 'approved')], default=1),
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='hd_app_sts',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Clarification needed'), (5, 'Skipped')], default=1),
        ),
        migrations.AlterField(
            model_name='raise_request_documentation',
            name='tag_confirm_type',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Clarification needed'), (3, 'Skipped'), (4, 'Tag assigned for developer for future work')], default=1),
        ),
    ]
