# Generated by Django 5.1 on 2024-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_raise_request_documentation_approve_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lead_managements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sources_of_lead', models.CharField(blank=True, max_length=500, null=True)),
                ('bussiness_name', models.CharField(blank=True, max_length=500, null=True)),
                ('bussiness_type', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_number', models.IntegerField(blank=True, max_length=10, null=True)),
                ('alternate_contact_number', models.IntegerField(blank=True, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('client_behaviour', models.IntegerField(choices=[(1, 'Positive'), (2, 'Negative'), (3, 'Neutral'), (4, 'Others')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
