# Generated by Django 5.1 on 2024-09-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_lead_managements'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_managements',
            name='call_connected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
