# Generated by Django 5.1 on 2024-09-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_lead_managements_call_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_managements',
            name='emp_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
