# Generated by Django 5.1 on 2024-09-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_lead_managements_emp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead_managements',
            old_name='address',
            new_name='full_address',
        ),
        migrations.RenameField(
            model_name='lead_managements',
            old_name='sources_of_lead',
            new_name='sources_of_leads',
        ),
    ]
