# Generated by Django 5.1 on 2024-09-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_address_lead_managements_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_managements',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
