# Generated by Django 5.1 on 2024-09-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_lead_managements_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_managements',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
