

from django.urls import path,include
from . import views
# urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
urlpatterns = [
    path('get_request_api/',views.Managerapprovalview.as_view(),name="get-request-data"),
    path('raise_request_api/',views.Requestview.as_view(),name="raise-request"),
    path('get_data/',views.DeveloperApprovalView.as_view(),name="get-data"),
    path('update_request/',views.Updatemanagerapprovalview.as_view(),name="update-request"),
    path('lead_managements_api/',views.LeadManagementsView.as_view(),name="lead-managements"),
    path('get_lead_managements_data/',views.LeadManagementsData.as_view(),name="lead-managements-data"),
    
    path('history_api/',views.Historyview.as_view(),name="history-view"),
    path('register_api/', views.RegisterView.as_view(), name='register'),
    path('login_api/', views.LoginView.as_view(), name='login'),
    path('register/', views.Register_form, name = "register"),
    path('dashboard/', views.dashboard_view, name = "dashboard"),
    path('',views.login_form,name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),  # Add URL pattern for logout
    path('api/user-data/', views.UserDataView.as_view(), name='user-data'),
    path('add-user/',views.dashboard_add_user,name="add-user"),
    path('alert/',views.dashboard_alert,name="alert"),
    path('assign-role/',views.dashboard_assign_role,name="assign-role"),
    path('avatar/',views.dashboard_avatar,name="avatar"),
    path('badges/',views.dashboard_badges,name="badges"),
    path('button/',views.dashboard_button,name="button"),
    path('calendar-main/',views.dashboard_calendar_main,name="calendar-main"),
    path('calendar/',views.dashboard_calendar,name="calendar"),
    path('card/',views.dashboard_card,name="card"),
    path('carousel/',views.dashboard_carousel,name="carousel"),
    path('chat-empty/',views.dashboard_chat_empty,name="chat-empty"),
    path('chat-message/',views.dashboard_chat_message,name="chat-message"),
    path('chat-profile/',views.dashboard_chat_profile,name="chat-profile"),
    path('code-generator-new/',views.dashboard_code_generator_new,name="code-generator-new"),
    path('code-generator/',views.dashboard_code_generator,name="code-generator"),
    path('colors/',views.dashboard_colors,name="colors"),
    path('column-chart/',views.dashboard_column_chat,name="column-chart"),
    path('company/',views.dashboard_company,name="company"),
    path('currencies/',views.dashboard_currencies,name="currencies"),
    path('developer-manager-approval',views.dashboard_developer_manager_approval, name="developer-manager-approval"),
    path('dropdown/',views.dashboard_dropdown,name="dropdown"),
    path('email/',views.dashboard_email,name="email"),
    path('error/',views.dashboard_error,name="error"),
    path('faq/',views.dashboard_faq,name="faq"),
    path('forgot-password/',views.dashboard_forgot_password,name="forgot-password"),
    path('form-validation/',views.dashboard_form_validation,name="form-validation"),
    path('form-layout/',views.dashboard_form_layout,name="form-layout"),
    path('form/',views.dashboard_form,name="form"),
    path('gallery/',views.dashboard_gallery,name="gallery"),
    path('image-generator/',views.dashboard_image_generator,name="image-generator"),
    path('image-upload/',views.dashboard_image_upload,name="image-upload"),
    path('index-2/',views.dashboard_index_2,name="index-2"),
    path('index-3/',views.dashboard_index_3,name="index-3"),
    path('index-4/',views.dashboard_index_4,name="index-4"),
    path('index-5/',views.dashboard_index_5,name="index-5"),
    path('index-6/',views.dashboard_index_6,name="index-6"),
    path('invoice-add/',views.dashboard_invoice_add,name="invoice-add"),
    path('invoice-edit/',views.dashboard_invoice_add,name="invoice-edit"),
    path('invoice-list/',views.dashboard_invoice_list,name="invoice-list"),
    path('invoice-preview/',views.dashboard_invoice_add,name="invoice-preview"),
    path('kanban/',views.dashboard_kanban,name="kanban"),
    path('raise-request/',views.dashboard_raise_request,name="raise-request"),
    path('manager-approval/',views.dashboard_manager_approval,name="manager-approval"),
    path('lead-managements/',views.dashboard_lead_managements,name="lead-managements"),
     path('lead-managements-data/',views.dashboard_lead_managements_data,name="lead-managements-data"),
    path('language/',views.dashboard_language,name="language"),
    path('line-chart/',views.dashboard_line_chart,name="line-chart"),
    path('list/',views.dashboard_list,name="list"),
    path('marketplace-details/',views.dashboard_marketplace_details,name="marketplace-details"),
    path('marketplace/',views.dashboard_marketplace,name="marketplace"),
    path('notification/',views.dashboard_notification,name="notification"),
    path('notification-alert/',views.dashboard_notification_alert,name="notification-alert"),
    path('pagination/',views.dashboard_pagination,name="pagination"),
    path('payment-gateway/',views.dashboard_payment_gateway,name="payment-gateway"),
    path('pie-chart/',views.dashboard_pie_chart,name="pie-chart"),
    path('portfolio/',views.dashboard_portfolio,name="portfolio"),
    path('pricing/',views.dashboard_pricing,name="pricing"),
    path('progress/',views.dashboard_progress,name="progress"),
    path('radio/',views.dashboard_radio,name="radio"),
    path('role-access/',views.dashboard_role_access,name="role-access"),
    path('sign-in/',views.dashboard_sign_in,name="sign-in"),
    path('sign-up/',views.dashboard_sign_up,name="sign-up"),
    path('star-rating/',views.dashboard_star_rating,name="star-rating"),
    path('starred/',views.dashboard_starred,name="starred"),
    path('switch/',views.dashboard_switch,name="switch"),
    path('table-basic/',views.dashboard_table_basic,name="table-basic"),
    path('table-data/',views.dashboard_table_data,name="table-data"),
    path('tabs/',views.dashboard_tabs,name="tabs"),
    path('tags/',views.dashboard_tags,name="tags"),
    path('terms-condition/',views.dashboard_terms_condition,name="terms-condition"),
    path('text-generator-new/',views.dashboard_text_generator_new,name="text-generator-new"),
    path('text-generator/',views.dashboard_text_generator,name="text-generator"),
    path('theme/',views.dashboard_theme,name="theme"),
    path('tooltip/',views.dashboard_tooltip,name="tooltip"),
    path('typography/',views.dashboard_typography,name="typography"),
    path('users-grid/',views.dashboard_users_grid,name="users-grid"),
    path('users-list/',views.dashboard_users_list,name="users-list"),
    path('view-details/',views.dashboard_view_details,name="view-details"),
    path('video-generator/',views.dashboard_video_generator,name="video-generator"),
    path('videos/',views.dashboard_videos,name="videos"),
    path('view-profile/',views.dashboard_view_profile,name="view-profile"),
    path('voice-generator/',views.dashboard_voice_generator,name="voice-generator"),
    path('wallet/',views.dashboard_wallet,name="wallet"),
    path('widgets/',views.dashboard_widgets,name="widgets"),
    path('wizard/',views.dashboard_wizard,name="wizard"),
    
    
    

 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
